# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Smoothing using exponential weighted moving average
#'
#' @inheritParams ewma_cc
#' @return `vector<numeric`: The smoothed series
#'
#' @import Rcpp
#'
#' @export
ewma_smoothing <- function(x, lambda) {
    .Call(`_controlcharts_ewma_smoothing`, x, lambda)
}

